# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  demands: npm

steps: 
- script: |
    echo Installing sfdx-cli
    npm install sfdx-cli --local
-script: 'sfdx --version'